[workspace]
resolver = "2"

members = [
    "rust/dcp023",
    "rust/dcp096",
    "rust/dcp101", "rust/dcp212", "rust/dcp241", "rust/dcp248", "rust/dcp269", "rust/dcp348", "rust/dcp350", "rust/dcp376", "rust/dcp377",
]
